### ISSUE TITLE
Changing loading-bar location?

### ISSUE THREAD

**Issue by andhof-mt** [caarlos0/nprogress-rails#26]
Hey, 

I like your spinner - but I have one (hopefully easy) question in regards to its customization:

If it possible to set where the loading bar loads? I am using a bootstrap navbar and would prefer the loading bar to be right below the navbar instead of on top of it. Is this possible?

Thanks

**Comment by caarlos0** [comment]
Yeah, this is just a wrapper to the original lib...

But I believe you can follow [this](https://github.com/rstacruz/nprogress#parent).
