### ISSUE TITLE
Ajax responder for prototype

### ISSUE THREAD

**Issue by cllns** [caarlos0/nprogress-rails#27]
Hey there,
I just added nprogress-rails to a legacy app which still uses Prototype. Here's the a version of `nprogress-ajax` that works with the Ajax events from Prototype. Feel free to include it in the package (maybe call it `nprogress-ajax-prototype`?), but I understand if you don't want to, since it's such a small niche. Regardless, I just wanted to document it here for anyone else who might need it.

(The normal jQuery one only works for Ajax events started by jQuery, so even though my app has the two co-existing, that one doesn't work).

```
Ajax.Responders.register({
  onCreate: function() {
    NProgress.start();
  },
  onComplete: function() {
    NProgress.done();
  }
});
```

**Comment by caarlos0** [comment]
Nice! Don't you want to open a PR with that? You can also add something in the README about it :beers:

**Comment by cllns** [comment]
Sure thing! Just wasn't sure if you were interested. I'll do this now.

**Comment by cllns** [comment]
Here you go! #28 

Feel free to change the wording of the README at your discretion!
