### ISSUE TITLE
How to deal with Turbolinks 3.0?

### ISSUE THREAD

**Issue by ginolon** [caarlos0/nprogress-rails#32]
I'm using it in one of my projects and it's a pain. I have two bar. I have to disable tubolinks 3.0's bar to show your one. How to style the default bar?

**Comment by caarlos0** [comment]
Turbolinks, as far as I know, doesn't have any bars... maybe you are confusing it with something else?

**Comment by metaskills** [comment]
Turbolinks 3 does have a progress bar. https://github.com/rails/turbolinks#progress-bar

**Comment by caarlos0** [comment]
@metaskills nice...

**Comment by metaskills** [comment]
Yea, so what I have done is just called `Turbolinks.ProgressBar.disable();` and allow this gem to take control using `nprogress-turbolinks.js`. Perhaps that file should have some code at the top to do this for everyone automatically. For example:

```javascript
if (Turbolinks.ProgressBar) { Turbolinks.ProgressBar.disable(); }
```

**Comment by caarlos0** [comment]
@metaskills that would be nice!

can you open a pull request with that?

**Comment by metaskills** [comment]
Will do!

**Comment by caarlos0** [comment]
@metaskills thanks!

**Comment by ginolon** [comment]
What differences from this to the original Turbolink's progress bar?

**Comment by caarlos0** [comment]
@ginolon can't tell, never used the new turbolinks...
