### ISSUE TITLE
couldn't find file 'nprogress'

### ISSUE THREAD

**Issue by Jirka1111** [caarlos0/nprogress-rails#40]
I have needed to deploy app via Capistrano. There was a problem with precompile of assets, so I have deleted files from downloaded template and deleted all from application.js and application.css. Now I want to debug app by adding one files per rake assets:precompile, but still have this issue.

Application.js:

//= require turbolinks
//= require nprogress
//= require nprogress-turbolinks

Application.css:

 *= require nprogress
 *= require nprogress-bootstrap
@import "nprogress";

```
Sprockets::FileNotFound in Home#index
Showing /Users/user/app/app/views/layouts/application.html.erb where line #6 raised:

couldn't find file 'nprogress'
  (in /Users/user/app/app/assets/stylesheets/application.css:13)
Extracted source (around line #6):
3
4
5
6
7
8
9
          
  <!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
  <html>
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
```

Am I missing something? Is there some file nprogress which I have deleted as well? Or is this nprogress error? And yes, I have restarted server (actually many times).

**Comment by caarlos0** [comment]
Which rails version?

Also, check this: https://github.com/caarlos0/nprogress-rails/issues/9

Anyways, I don't think this is a nprogress-rails issue. You can try to remove nprogress-rails and see if something else breaks to be sure.

**Comment by Jirka1111** [comment]
This only leeds to:

```
Sprockets::FileNotFound in Home#index
Showing /Users/user/app/app/views/layouts/application.html.erb where line #6 raised:

couldn't find file 'nprogress' with type 'text/css'
Extracted source (around line #6):
3
4
5
6
7
8
9
          
  <!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
  <html>
  <head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
```

**Comment by Jirka1111** [comment]
Sorry, Rails 4.1.14
