### ISSUE TITLE
Turbolinks and Full Page Loads

### ISSUE THREAD

**Issue by atarantino** [caarlos0/nprogress-rails#41]
My rails website leverages turbolinks for the majority of the application, but for a few links I do not use turbolinks because it seems to break some jquery/js functionality (jquery-turbolinks gem doesn't resolve those bugs either)

So is it possible to use this for page loads with and without turbolinks? I can only seem to get it to work one way or the other. 

Thanks

**Comment by caarlos0** [comment]
It won't work for full page loads, since no AJAX event is triggered...
