### ISSUE TITLE
nprogress-turbolinks incompatible with Turbolinks 5.0.0

### ISSUE THREAD

**Issue by rafael-fernandes** [caarlos0/nprogress-rails#42]
Hey, nprogress-turbolinks is incompatible with turbolinks 5.0.0 because the events changed.

The new list of events can be checked here: https://github.com/turbolinks/turbolinks#full-list-of-events

I hope it update because it's a very good gem!

Thank you.

**Comment by caarlos0** [comment]
can you open a pull request?

**Comment by dixpac** [comment]
@rafael-fernandes  @caarlos0  not 100% but is there progress now natively in TL5?

**Comment by rafael-fernandes** [comment]
@dixpac yeah, https://github.com/turbolinks/turbolinks#displaying-progress

@caarlos0 
I fixed the incompatibility with this script in Turbolinks git:
https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/compatibility.coffee

Maybe u can add the link in README for the people that use Turbolinks > 5.0.0

**Comment by CronJavaNow** [comment]
This is what I ended up coming up with, this also includes the back button (fix)

`(document).addEventListener('turbolinks:request-start', function () {
    NProgress.start();
});

document.addEventListener("turbolinks:load", function () {
    NProgress.done();
});

document.addEventListener("turbolinks:request-end", function () {
    NProgress.remove();
});

document.addEventListener("turbolinks:before-cache", function() {
    NProgress.remove();
});`

**Comment by caarlos0** [comment]
can you guys test if #44 works for you?

**Comment by Cervajz** [comment]
Works for me 👍

**Comment by caarlos0** [comment]
Pushed v0.1.6.8
