### ISSUE TITLE
Change Nprogress bar location

### ISSUE THREAD

**Issue by vickykrbu** [caarlos0/nprogress-rails#43]
I am running one mvc 4 application where i have navbar in my layout.cshtml page. I recently added N progress from [here](https://github.com/rstacruz/nprogressl) for one of my view to show progress bar when page loads. in that view i have one div. When i run my application progress bar is showing up of navbar. But i wanted to show progress bar below of the div. How would i achieve the same?

**Comment by caarlos0** [comment]
That's a question for the repo of the original lib: https://github.com/rstacruz/nprogress

**Comment by vickykrbu** [comment]
Hi caarlos0 I have seen this answer but i want to know where to add this line to change location? Please help me.

**Comment by vickykrbu** [comment]
I got the solution that Nprogress configure code needs to put very first of the script has been used in the page.
