### ISSUE TITLE
Turbolinks.ProgressBar.disable is not a function

### ISSUE THREAD

**Issue by duet-ngyen** [caarlos0/nprogress-rails#47]
I'm trying to use this gem. 
Gemfile
gem 'nprogress-rails'

application.css.scss
*= require_tree .
 *= require_self
 *= require nprogress
*= require nprogress-bootstrap

application.js
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require nprogress
//= require nprogress-turbolinks
//= require_tree .

but it's not work
![screenshot from 2016-08-05 13 24 15](https://cloud.githubusercontent.com/assets/11748904/17428093/ed7093f2-5b0f-11e6-9b44-7ecb490d58a7.png)

**Comment by caarlos0** [comment]
This was already fixed, but I forgot to release it.

Doing it right now...

**Comment by caarlos0** [comment]
Please use the version `0.2.0.2`. 

Thanks
