### ISSUE TITLE
Provide a method to change the progress bar delay

### ISSUE THREAD

**Issue by mrkongo** [caarlos0/nprogress-rails#48]
Why nprogress doesn't have something like this?

turbolinks/turbolinks#124

and this:

turbolinks/turbolinks-classic#604

and this:

turbolinks/turbolinks-classic#608

**Comment by caarlos0** [comment]
Because it's not in the nprogress API: http://ricostacruz.com/nprogress/

**Comment by mrkongo** [comment]
It's not a valid reason. Gen can have something similar to turbolinks feature. I opened the same issue/request to nprogress repo. Please do not close it. Assign a "request" label. It's an important feature.
